export const GET_DISCUSSIONS_REQUEST = 'GET_DISCUSSIONS_REQUEST';
export const GET_DISCUSSIONS_SUCCESS = 'GET_DISCUSSIONS_SUCCESS';
export const GET_DISCUSSIONS_FAILURE = 'GET_DISCUSSIONS_FAILURE';


export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
